version: '3.9'
services:
  datasetenricher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8060:80
      - 7060:443
    environment:
      - Serilog__MinimumLevel=Debug
      - GleiApiConfiguration__BaseUrl=https://api.gleif.org/
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7060
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
      
